# Use a node base image
FROM node:latest

# Set the working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@latest

# Add app
COPY . /app

# Start the app
CMD ng serve --host 0.0.0.0