# Use a Maven base image
FROM maven:3.6.3-jdk-11-slim AS build

# Set the working directory
WORKDIR /app

# Copy source code to image
COPY src /app/src
COPY pom.xml /app

# Package the application
RUN mvn -f /app/pom.xml clean package

# Use OpenJDK for running the application
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/api-0.0.1-SNAPSHOT.jar /app/api.jar

# Expose port
EXPOSE 8080

# Run the jar file 
ENTRYPOINT ["java","-jar","api.jar"]