# Use a Gradle base image compatible with Java 17
FROM gradle:7.3.3-jdk17 AS build

# Set the working directory
WORKDIR /app

# Copy the Gradle configuration files
COPY build.gradle settings.gradle /app/

# Copy the source code
COPY src /app/src

# Build the application
RUN gradle build -x test --no-daemon

# Use a JDK 17 image for running the application
FROM openjdk:17-slim as runtime
WORKDIR /app
COPY --from=build /app/build/libs/*.jar /app/api.jar

# Expose port
EXPOSE 8080

# Run the jar file 
ENTRYPOINT ["java","-jar","api.jar"]
